### ISSUE TITLE
Create new class "pathogen evolution model"

### ISSUE THREAD

**Issue by hoganwr** [ApolloDev/apollo-sv#91]

**Comment by hoganwr** [comment]
Create a new class with rdfs:label "pathogen evolution model".  
Editor preferred term: "model of evolution of species of organism with infectious disposition" 
Parent class: algorithm
Approximate definition that likely requires refinement (ADLRR, pronounced "adler"): "an algorithm that simulates the evolution of a particular species, at least some of whose instances in time bear an infectious disposition, over time."

**Comment by dillerm** [comment]
I think the definition might read better if you moved 'over time' so that it comes after 'simulates'. Also, because our definition of 'pathogen' stipulates that the organism be a bearer of an infectious disposition, would it be ok to simply state that the it simulates the evolution of a particular pathogen species?

**Comment by hoganwr** [comment]
The "over time" modifies "evolution" not "simulates" so how about:

"simulation software that simulates the evolution over time of a particular pathogen of a particular biological taxon"

Making it taxon in case the software is simulating at the genus or higher level.

**Comment by dillerm** [comment]
Looks good. I don't see any other reasons to modify it, either.

**Comment by hoganwr** [comment]
Great.  We'll go with it for now, then.

**Comment by dillerm** [comment]
I didn't catch this earlier, but in your change to the first proposal you replaced the original parent class of 'algorithm' with 'simulation software'. I imagine this was an accident, right?

**Comment by hoganwr** [comment]
Not sure but I don't think so.

We need to be careful to distinguish them.  DTMs were originally under
algorithm, but in the MIDAS Digital Commons they've been moved to
software.  Most of these new classes should be under software.

We probably need to decide what to do about DTMs.

**Comment by dillerm** [comment]
That might be problematic since models and software are two distinct types of entities. To wit, GLEaMviz is a software created for running simulations using the GLEaM model, which is "a stochastic computational scheme that integrates worldwide high-resolution demographic and mobility data to simulate disease spread on the global scale."

Source: http://bmcinfectdis.biomedcentral.com/articles/10.1186/1471-2334-11-37

**Comment by hoganwr** [comment]
Yes Mike and I have had various discussions about the ontology here.

We agreed that for the initial standup of the Digital Commons, we weren't
going to have time to tease out the distinctions.

But GLEAM (the model) is implemented as GLEAM (the software).

Not sure it's worth teasing out that distinction.  That is, what is the
practical use case?

**Comment by dillerm** [comment]
Will go ahead with the most recent update to the definition, and will make the editor preferred term 'pathogen evolution model software'.
