### ISSUE TITLE
Create new class "disease forecasting software"

### ISSUE THREAD

**Issue by hoganwr** [ApolloDev/apollo-sv#95]
rdfs:label "disease forecasting software"
alternative term "disease forecasting"
alternative term "disease transmission forecasting"
editor preferred term: "software that forecasts disease transmission"
parent class: software
ADLRR: "software that has as output one or more count data items that are about a host population and that predict how many infections will occur at or will have occurred by some time in the future relative to when the data items are created."

**Comment by dillerm** [comment]
How about this:

"Simulation software that has as output one or more count-of-simulated-contagious-population [probably want to change the rdfs:label to 'count of simulated infectious population' so that it's more in line with the terminology used by modelers] and that predict the number of infections that will occur at or will have occurred by some time in the future relative to when the data items are created."

**Comment by hoganwr** [comment]
I like changing the parent class to simulation software.  SImulated populations are out favor, and thus by extension are counts of them.

So: "Simulation software that has as output one or more count data items that are about a host population and that predict how many infections will occur at or will have occurred by some time in the future relative to when the data items are created."

**Comment by dillerm** [comment]
I agree that 'host population' is better to use here, although I'm now wondering whether the output would be a predicted data item.

**Comment by dillerm** [comment]
We arrived at a consensus that the definition should be "Simulation software that has as output one or more predicted count data items that are about a host population and that predict how many infections will occur at or will have occurred by some time in the future relative to when the data items are created." Just need to add class now.
